#!/usr/bin/env python3

import rclpy
from rclpy.node import Node

class PlaceholderNode(Node):
    pass

def main():
    rclpy.init()
    node = PlaceholderNode(
        "launch_manager",
        start_parameter_services=False
    )
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass

    try:
        rclpy.shutdown()
    except:
        pass

if __name__ == '__main__':
    main()
